title: IrisSec Computer Hacking Club
description: Based primarily in the United States, we have members from multiple colleges, universities, and companies all across the country. We serve as a hub for educational, professional, and human connections for passionate hackers of all walks of life. We are the IrisSec Computer Hacking Club.

permalink: /articles/categories/:categories/:year-:month-:day/:title
paginate: 10
paginate_path: /articles/page:num/

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  members:
    output: true
    permalink: /:collection/:name
  categories:
    output: true
    permalink: /articles/:collection/:name

plugins:
  - jekyll-paginate
